# Étape de base
FROM node:20-alpine

# Définition du répertoire de travail
WORKDIR /app

# Copie des fichiers de configuration
COPY package*.json ./
COPY vite.config.js ./
COPY vitest.config.js ./

# Installation des dépendances et correction des vulnérabilités
RUN npm install

# Copie du reste du code source
COPY . .

# Exposition du port
EXPOSE 5001

# Configuration de l'environnement
ENV NODE_ENV=development
ENV VITE_SERVER_HOST=0.0.0.0
ENV VITE_SERVER_PORT=5001

# Commande par défaut pour le développement
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5001"]
